# Generated by Django 4.1.3 on 2022-11-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_locations_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='locations',
        ),
    ]
