# Generated by Django 4.1.3 on 2022-11-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_location_user_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location_id',
        ),
    ]
