# Generated by Django 4.1.3 on 2022-11-30 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('(^(\\d?|[a-zа-я]?|[A-ZА-Я]?|[?=.*]?){6,}$')]),
        ),
    ]
