# Generated by Django 4.1.3 on 2022-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'member'), ('Администратор', 'admin'), ('Модератор', 'moderator')], default='member', max_length=20),
        ),
    ]
