# Generated by Django 4.1.3 on 2022-11-30 12:09

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True, validators=[users.validators.email_validator]),
        ),
    ]
