# Generated by Django 4.1.3 on 2022-11-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_location_remove_ad_author_ad_category_id_ad_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
    ]
