# Generated by Django 4.1.3 on 2022-11-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='ads',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='user',
            new_name='owner',
        ),
    ]
