# Generated by Django 4.1.3 on 2022-11-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_user_age_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
