# Generated by Django 4.1.3 on 2022-11-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='address',
        ),
    ]
